### ISSUE TITLE
Set up discourse

### ISSUE THREAD

**Issue by bromagosa** [bromagosa/beetleCloud#53]

**Comment by bromagosa** [comment]
Check out https://github.com/discourse/discourse/blob/master/docs/INSTALL-email.md

**Comment by cycomachead** [comment]
Awesome, are you planning to build the SSO features for Discourse?

I setup one for Snap! recently using SparkPost and it wasn't too bad.

http://snapforum.cs10.org - I can add you but not much has gone on yet.

**Comment by bromagosa** [comment]
Yep, that was the idea!

Do you think you could help here? I worked on this yesterday and couldn't manage. Problem is we're using that same server for the BeetleCloud, and Discourse seems to want port 80 all for itself. I disabled the BeetleCloud for a while just to get the installation process going, hoping to be able to redirect it to some other port when done, but the thing is Discourse and the BeetleCloud also share the same PostgreSQL database, which I suspect is what made the install script complain and abort...

Maybe the smartest thing would be to use a separate server for Discourse?

**Comment by bromagosa** [comment]
(related: https://github.com/bromagosa/beetleCloud/issues/58)

**Comment by cycomachead** [comment]
I used DigitalOcean to setup Discourse, since we needed some external host. 

It seems like you'll definitely want to use a subdomain for discourse - so I think you can use the same machine, though you'll probably need to some configuration do that both Discourse and BeetleCloud don't use the same DB file. 

What I might try is the Docker version of discourse, which should just be able to run as a self-contained container (is that redundant??), and won't touch any of the BeetleCloud stuff.

I haven't done too much with Docker, though. But I think once you get the container running you could use the main nginx config to expose that port as a subdomain. 

Some stuff I looked at that might help:

https://www.digitalocean.com/community/tutorials/how-to-install-discourse-behind-nginx-on-ubuntu-14-04
https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-virtual-hosts-server-blocks-on-ubuntu-12-04-lts--3
https://github.com/jwilder/nginx-proxy

**Comment by cycomachead** [comment]
Oh and of course, this one:

https://github.com/discourse/discourse_docker

The "advanced" section has a multisite configuration document too that seems helpful.
